#!/bin/bash
# change perms on dir
sudo chmod -R 777 /home/ec2-user/acebook-es

# navigate into our working directory where we have all our github files
cd /home/ec2-user/acebook-es

# add npm + node to path
export NVM_DIR="$HOME/.nvm" 
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # loads nvm 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # loads nvm bash_completion (node is in path now)

# install node modulles
npm install

# start node app in the background
npm start &> app.out.log &

# start mongodb, enable it on boot, show status
sudo systemctl start mongod
sudo systemctl enable mongod
sudo systemctl status mongod