name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGODB_URL: mongodb://localhost:27017/acebook_test
      PORT: 3030

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: until nc -z localhost 27017; do sleep 1; done

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests with increased timeout
        run: npm run test:unit -- --testTimeout=30000

      - name: Start application
        run: npm start &

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3030

      - name: Run integration tests
        run: npm run test:integration

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
      S3_BUCKET: es-acebook-bucket
      CODEDEPLOY_APPLICATION_NAME: es-acebook
      CODEDEPLOY_DEPLOYMENT_GROUP: es-production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user

      - name: Create application archive zip
        run: zip -r acebook.zip .

      - name: Upload application archive to S3
        run: aws s3 cp acebook.zip s3://es-acebook-bucket

      - name: Deploy Application with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "$CODEDEPLOY_APP" \
            --deployment-group-name "$CODEDEPLOY_GROUP" \
            --s3-location "bucket=$S3_BUCKET,key=acebook.zip,bundleType=zip" \
            --region "$AWS_REGION"
