name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGODB_URL: mongodb://localhost:27017/acebook_test
      PORT: 3030
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: until nc -z localhost 27017; do sleep 1; done

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests with increased timeout
        run: npm run test:unit -- --testTimeout=30000

      - name: Start application
        run: npm start &

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3030

      - name: Run integration tests
        run: npm run test:integration

      - name: Create application archive
        run: tar -czf acebook.tar.gz .

      - name: Upload application archive to S3
        run: aws s3 cp acebook.tar.gz s3://es-acebook-bucket
